import {
  AppWindow,
  Bell,
  BookOpen,
  Boxes,
  Building2,
  Calculator,
  Calendar,
  Camera,
  ChartColumn,
  ChartLine,
  ChartPie,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cog,
  Container,
  Database,
  Euro,
  Factory,
  FileSpreadsheet,
  FileText,
  Folder,
  Forklift,
  Globe,
  GraduationCap,
  Hammer,
  HardHat,
  House,
  KeyRound,
  Landmark,
  LayoutDashboard,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  MessageSquare,
  Package,
  Receipt,
  Ruler,
  Scale,
  Search,
  Settings,
  ShieldCheck,
  Star,
  Store,
  Tag,
  Truck,
  Users,
  Warehouse,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Nom de l'icône de repli (valeur par défaut d'une application). */
export const FALLBACK_ICON_NAME = "app-window";

/**
 * Registre explicite des icônes disponibles pour les applications (nom lucide
 * en kebab-case). Importer toute la bibliothèque alourdirait le bundle : pour
 * ajouter une icône, l'importer ci-dessus et l'ajouter ici (voir
 * `docs/CATALOGUE.md`).
 */
const ICON_REGISTRY: Record<string, LucideIcon> = {
  "app-window": AppWindow,
  bell: Bell,
  "book-open": BookOpen,
  boxes: Boxes,
  "building-2": Building2,
  calculator: Calculator,
  calendar: Calendar,
  camera: Camera,
  "chart-column": ChartColumn,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  cog: Cog,
  container: Container,
  database: Database,
  euro: Euro,
  factory: Factory,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  folder: Folder,
  forklift: Forklift,
  globe: Globe,
  "graduation-cap": GraduationCap,
  hammer: Hammer,
  "hard-hat": HardHat,
  house: House,
  "key-round": KeyRound,
  landmark: Landmark,
  "layout-dashboard": LayoutDashboard,
  "list-checks": ListChecks,
  lock: Lock,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  "message-square": MessageSquare,
  package: Package,
  receipt: Receipt,
  ruler: Ruler,
  scale: Scale,
  search: Search,
  settings: Settings,
  "shield-check": ShieldCheck,
  star: Star,
  store: Store,
  tag: Tag,
  truck: Truck,
  users: Users,
  warehouse: Warehouse,
  wrench: Wrench,
  zap: Zap,
};

/** Noms d'icônes proposables (liste de choix du formulaire d'administration, étape 5), sans doublon. */
export const ICON_NAMES: readonly string[] = Object.keys(ICON_REGISTRY).sort();

/** Retourne l'icône du registre ; un nom inconnu retombe sur `app-window` sans erreur. */
export function resolveIcon(name: string | null | undefined): LucideIcon {
  const icon = name ? ICON_REGISTRY[name] : undefined;
  return icon ?? (ICON_REGISTRY[FALLBACK_ICON_NAME] as LucideIcon);
}
